export const countries = [
  { name: "India", code: "IN", dial_code: "+91" },
  { name: "United States", code: "US", dial_code: "+1" },
  { name: "United Kingdom", code: "GB", dial_code: "+44" },
  { name: "Canada", code: "CA", dial_code: "+1" },
  { name: "Australia", code: "AU", dial_code: "+61" },
  { name: "United Arab Emirates", code: "AE", dial_code: "+971" },
  { name: "Singapore", code: "SG", dial_code: "+65" },
  { name: "Germany", code: "DE", dial_code: "+49" },
  { name: "France", code: "FR", dial_code: "+33" },
  { name: "Japan", code: "JP", dial_code: "+81" },
  { name: "China", code: "CN", dial_code: "+86" },
  { name: "Brazil", code: "BR", dial_code: "+55" },
  { name: "South Africa", code: "ZA", dial_code: "+27" },
  { name: "Russia", code: "RU", dial_code: "+7" },
  { name: "Italy", code: "IT", dial_code: "+39" },
  { name: "Spain", code: "ES", dial_code: "+34" },
  { name: "Netherlands", code: "NL", dial_code: "+31" },
  { name: "Sweden", code: "SE", dial_code: "+46" },
  { name: "Switzerland", code: "CH", dial_code: "+41" },
  { name: "Other", code: "globe", dial_code: "" },
];
